{{- if (not (or .Values.mariadb.enabled .Values.externalDatabase.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "externaldb"  }}
  labels:
    app: {{ printf "%s-%s" .Release.Name "externaldb"  }}
    chart: {{ template "osclass.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  mariadb-password: {{ default "" .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
